name: llamaware-agent
description: automated health checks and issue management

features:
  - health_checks
  - todo_management  
  - milestone_assignment

permissions:
  contents: read
  pull-requests: write
  issues: write