security:
  - changed-files:
      - any-glob-to-any-file:
          - '**/auth*'
          - '**/password*'
          - '**/token*'
          - '**/credential*'
          - '**/secret*'
          - '**/jwt*'
          - '**/oauth*'
      - any-glob-to-any-file:
          - '.env*'
          - 'secrets/**'
          - 'credentials/**'

docs:
  - changed-files:
      - any-glob-to-any-file: ['*.md', '*.rst', '*.txt', 'docs/**', 'documentation/**']

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '**/Dockerfile*'
          - 'docker-compose*'
      - any-glob-to-any-file:
          - '.gitlab-ci*'
          - '.travis*'
          - 'Jenkinsfile*'
          - 'Makefile'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.json'
          - '*.toml'
          - '*.ini'
          - '*.cfg'
          - '*.conf'
      - any-glob-to-any-file:
          - 'package.json'
          - 'pyproject.toml'
          - 'Cargo.toml'
          - 'go.mod'
          - 'Gemfile'
      - any-glob-to-any-file:
          - 'tsconfig.json'
          - '.eslintrc*'
          - '.prettierrc*'
          - '.editorconfig'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'test/**'
          - 'tests/**'
          - '__tests__/**'
          - 'spec/**'
          - '*.test.*'
          - '*.spec.*'
          - 'test_*.py'
          - '*_test.go'
