networks:
  e2e-network:
    driver: bridge

services:
  mock-together:
    image: nginx:alpine
    entrypoint: ["/bin/sh", "/start_nginx.sh"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "--spider", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: mock-together
    environment:
      - MOCK_TYPE=together
    ports:
      - "8081:80"
    volumes:
      - ./tests/mocks/start_nginx.sh:/start_nginx.sh:ro
    networks:
      - e2e-network

  mock-cerebras:
    image: nginx:alpine
    entrypoint: ["/bin/sh", "/start_nginx.sh"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "--spider", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: mock-cerebras
    environment:
      - MOCK_TYPE=cerebras
    ports:
      - "8082:80"
    volumes:
      - ./tests/mocks/start_nginx.sh:/start_nginx.sh:ro
    networks:
      - e2e-network

  mock-fireworks:
    image: nginx:alpine
    entrypoint: ["/bin/sh", "/start_nginx.sh"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "--spider", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: mock-fireworks
    environment:
      - MOCK_TYPE=fireworks
    ports:
      - "8083:80"
    volumes:
      - ./tests/mocks/start_nginx.sh:/start_nginx.sh:ro
    networks:
      - e2e-network

  mock-groq:
    image: nginx:alpine
    entrypoint: ["/bin/sh", "/start_nginx.sh"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "--spider", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: mock-groq
    environment:
      - MOCK_TYPE=groq
    ports:
      - "8084:80"
    volumes:
      - ./tests/mocks/start_nginx.sh:/start_nginx.sh:ro
    networks:
      - e2e-network

  mock-deepseek:
    image: nginx:alpine
    entrypoint: ["/bin/sh", "/start_nginx.sh"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "--spider", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: mock-deepseek
    environment:
      - MOCK_TYPE=deepseek
    ports:
      - "8085:80"
    volumes:
      - ./tests/mocks/start_nginx.sh:/start_nginx.sh:ro
    networks:
      - e2e-network

  mock-openai:
    image: nginx:alpine
    entrypoint: ["/bin/sh", "/start_nginx.sh"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "--spider", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: mock-openai
    environment:
      - MOCK_TYPE=openai
    ports:
      - "8086:80"
    volumes:
      - ./tests/mocks/start_nginx.sh:/start_nginx.sh:ro
    networks:
      - e2e-network

  mock-ollama:
    image: nginx:alpine
    entrypoint: ["/bin/sh", "/start_nginx.sh"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "--spider", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: mock-ollama
    environment:
      - MOCK_TYPE=ollama
    ports:
      - "11434:80"
    volumes:
      - ./tests/mocks/start_nginx.sh:/start_nginx.sh:ro
    networks:
      - e2e-network

  e2e-tests:
    build:
      context: .
      dockerfile: package/docker/Dockerfile
      target: builder
    container_name: llamaware-e2e-tests
    depends_on:
      - mock-together
      - mock-cerebras
      - mock-fireworks
      - mock-groq
      - mock-deepseek
      - mock-openai
      - mock-ollama
    environment:
      - TOGETHER_API_KEY=test-key
      - CEREBRAS_API_KEY=test-key
      - FIREWORKS_API_KEY=test-key
      - GROQ_API_KEY=test-key
      - DEEPSEEK_API_KEY=test-key
      - OPENAI_API_KEY=test-key
      - SERPAPI_KEY=test-key
      - OLLAMA_HOST=http://mock-ollama:11434
      - TEST_MODE=1
      - BUILDKIT_INLINE_CACHE=1
    volumes:
      - .:/app
      - /app/build
      - /root/.cache
    working_dir: /app
    user: root
    command: ["bash", "-c", "ulimit -c unlimited && /app/tests/e2e/run_tests_in_docker.sh || touch /app/tests/e2e/.e2e_failed"]
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    stop_grace_period: 10s
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "true"]
      interval: 60s
      timeout: 5s
      retries: 1
    restart: "no"
    networks:
      - e2e-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
          pids: 1024
    tmpfs:
      - /tmp:exec,mode=1777