name: 'release'
description: 'creates github release'

inputs:
  token:
    description: 'github token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: version
      id: version
      shell: bash
      run: |
        VERSION=$(cat VERSION | tr -d '\n')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT

    - name: check
      id: tag_check
      shell: bash
      run: |
        if git tag -l | grep -q "^v${{ steps.version.outputs.version }}$"; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: tag
      if: steps.tag_check.outputs.exists == 'false'
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "v${{ steps.version.outputs.version }}" -m "release v${{ steps.version.outputs.version }}"
        git push origin "v${{ steps.version.outputs.version }}"

    - name: notes
      id: release_notes
      shell: bash
      run: |
        # get previous tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          PREVIOUS_TAG=$(git rev-list --max-parents=0 HEAD)
        fi

        # read template
        RELEASE_NOTES=$(cat .github/release-template.md | \
          sed "s/{previous_tag}/$PREVIOUS_TAG/g" | \
          sed "s/{current_tag}/v${{ steps.version.outputs.version }}/g")
        echo "notes<<EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: release ${{ steps.version.outputs.tag }}
        body: ${{ steps.release_notes.outputs.notes }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
